apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-demo
spec:
  selector:
    matchLabels:
      app: jenkins-demo
  template:
    metadata:
      labels:
        app: jenkins-demo
    spec:
      containers:
      - image: <DOCKERHUB_NAME>/<DOCKERHUB_REPO>/jenkins-demo:<BUILD_NUMBER>
        imagePullPolicy: IfNotPresent
        name: jenkins-demo
        ports: 
        - containerPort: 8080
        env:
        - name: branch
          value: <BRANCH_NAME>
        
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
spec:
  selector:
    app: jenkins-demo
  ports:
    - protocol: TCP
      type: NodePort
      port: 8080
      targetPort: 8080
<<<<<<< HEAD
      nodePort: 30100
=======
>>>>>>> 1a0f7ac3d30526073a53b2f726dc37fecf977b0d
