apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-demo
spec:
  selector:
    matchLabels:
      app: jenkins-demo
  template:
    metadata:
      labels:
        app: jenkins-demo
    spec:
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/huorepo/jenkins-demo:<BUILD_NUMBER>
        imagePullPolicy: IfNotPresent
        name: jenkins-demo
        port: 8080
        env:
        - name: branch
          value: <BRANCH_NAME>
        
---
apiVersion: apps/v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    matchLabels:
      app: jenkins-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080